export { ReactComponent as MoaLogo } from './moaDatalogo.svg'
export { ReactComponent as NoResult } from './noResult.svg'
export { ReactComponent as ExclamationIcon } from './exclamationIcon.svg'
export { ReactComponent as DashBoardBG } from './dashboard_background.svg'
export { ReactComponent as People } from './people.svg'
export { ReactComponent as Home } from './home.svg'
